### ISSUE TITLE
Bättre inloggning

### ISSUE THREAD

**Issue by dlidstrom** [dlidstrom/Snittlistan#608]
- Sida som visas efter lyckad inloggning 
- Felaktig kod visas inte i Pushover
- 7 dagar giltighet på koden

**Comment by dlidstrom** [comment]
Fixa

```
System.ArgumentException: Value cannot be null or empty.
Parameter name: url
at System.Web.Mvc.Controller.Redirect(String url)
at Snittlistan.Web.Areas.V2.Controllers.AuthenticationController.<LogOnOneTimePassword>d__6.MoveNext() in D:\a\Snittlistan\Snittlistan\Snittlistan.Web\Areas\V2\Controllers\AuthenticationController.cs:line 215
```

**Comment by dlidstrom** [comment]
Så här:

```html
<div class="alert alert-success">
  <strong>Du är uttagen till:</strong>
  <dl>
    <dt>Omgång 3</dt>
    <dd>
      <span class="label label-important">OBEKRÄFTAT</span>
    </dd>
    <dt>Omgång 5</dt>
    <dd>
      <span class="label label-success">BEKRÄFTAT</span>
    </dd>
  </dl>
</div>
```

**Comment by dlidstrom** [comment]
Du är uttagen visas fast det är preliminär match

**Comment by dlidstrom** [comment]
sortera omgångarna
